services:
  nginx:
    image: nginx:latest
    deploy:
      placement:
        constraints:
          - "node.labels.mylabel == web"
    ports:
      - "80:80"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
  
  db:
    image: postgres
    deploy:
      placement:
        constraints:
          - "node.labels.mylabel == bdd"
    environment:
      POSTGRES_PASSWORD: password
