services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    deploy:
      replicas: 5
      update_config:
        parallelism: 2
        delay: 10s
  
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password