[supervisord]
nodaemon=true
user=root

[program:sshd]
command=/bin/bash -c "mkdir -p /var/run/sshd && exec /usr/sbin/sshd -D"

[program:apache2]
command=/bin/bash -c "rm -f /var/run/apache2/apache2.pid && mkdir -p /var/run/apache2 /var/lock/apache2 && source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"

